//! Exercises `fn detect()` bodies and the resolver convention they enable.
//!
//! Two angles:
//! - Positive: every entrypoint with a `detect_entrypoint` must accept at
//!   least one in-repo positive sample.
//! - Negative: synthetic yaml inputs that look superficially like dialect
//!   candidates but lack the structural signal must be rejected.

use lsh::compiler::{Entrypoint, Generator, SerializedCharset};
use lsh::runtime::Runtime;
use stdext::arena::{Arena, scratch_arena};

/// Assemble once per test; the Generator's arena keeps the assembled bytecode
/// alive for the test's lifetime via the returned [`Built`].
struct Built<'a> {
    instructions: Vec<u8>,
    strings: Vec<&'a str>,
    charsets: Vec<SerializedCharset>,
    entrypoints: Vec<Entrypoint>,
}

fn build<'a>(arena: &'a Arena) -> Built<'a> {
    let mut generator = Generator::new(arena);
    generator.read_directory(lsh::compiler::builtin_definitions_path()).unwrap();
    let assembly = generator.assemble().unwrap();
    let charsets = assembly.charsets.iter().map(|cs| cs.serialize()).collect();
    Built {
        instructions: assembly.instructions,
        strings: assembly.strings,
        charsets,
        entrypoints: assembly.entrypoints,
    }
}

fn make_runtime<'b>(built: &'b Built<'b>) -> Runtime<'b, 'b, 'b> {
    Runtime::new(&built.instructions, &built.strings, &built.charsets, 0)
}

#[test]
fn slice_yaml_detect_positive() {
    let _ = stdext::arena::init(64 * 1024 * 1024);
    let arena = scratch_arena(None);
    let built = build(&arena);
    let mut runtime = make_runtime(&built);

    let slice_yaml =
        built.entrypoints.iter().find(|e| e.name == "slice_yaml").expect("slice_yaml ep");
    let detect_addr = slice_yaml.detect_address.expect("slice_yaml needs detect") as u32;

    // Minimal positive sample mirroring the chisel slice shape.
    let bash_yaml = b"\
package: bash

essential:
  bash_copyright:

slices:
  config:
    contents:
      /etc/bash.bashrc:
";
    assert!(runtime.detect(bash_yaml, detect_addr), "detect should accept bash.yaml shape");

    // Leading comments / blank lines must not derail the sniffer.
    let with_preamble = b"\
# auto-generated by chisel
# do not edit

package: libc6

essential:
  libc6_copyright:

slices:
  libs:
    contents:
      /lib/libc.so.6:
";
    assert!(runtime.detect(with_preamble, detect_addr), "comments + blanks before package: ok");
}

#[test]
fn slice_yaml_detect_negative() {
    let _ = stdext::arena::init(64 * 1024 * 1024);
    let arena = scratch_arena(None);
    let built = build(&arena);
    let mut runtime = make_runtime(&built);

    let slice_yaml =
        built.entrypoints.iter().find(|e| e.name == "slice_yaml").expect("slice_yaml ep");
    let detect_addr = slice_yaml.detect_address.expect("slice_yaml needs detect") as u32;

    // Plain yaml -- no `package:` first non-blank line.
    let plain = b"\
version: 2
jobs:
  build:
    runs-on: ubuntu-latest
";
    assert!(!runtime.detect(plain, detect_addr), "github actions yaml is not a slice");

    // docker-compose: `version:` first, again no `package:`.
    let compose = b"\
version: '3.8'
services:
  web:
    image: nginx
";
    assert!(!runtime.detect(compose, detect_addr), "docker-compose is not a slice");

    // Looks-like-package value but missing top-level `slices:` block (e.g.
    // an ansible variables file, or chisel-adjacent yaml that isn't an sdf).
    let no_slices = b"\
package: hello
description: a greeting

dependencies:
  - libc6
";
    assert!(!runtime.detect(no_slices, detect_addr), "package: without slices: is not a slice");

    // Empty buffer.
    assert!(!runtime.detect(b"", detect_addr), "empty buffer must not match");
}

/// Validate against a sample of the real chisel-releases corpus when it's
/// available locally. Skips silently otherwise so CI doesn't depend on it.
#[test]
fn slice_yaml_detect_corpus_sample() {
    let _ = stdext::arena::init(64 * 1024 * 1024);
    let arena = scratch_arena(None);
    let built = build(&arena);
    let mut runtime = make_runtime(&built);

    let slice_yaml =
        built.entrypoints.iter().find(|e| e.name == "slice_yaml").expect("slice_yaml ep");
    let detect_addr = slice_yaml.detect_address.expect("slice_yaml needs detect") as u32;

    let Some(home) = std::env::var_os("HOME") else {
        return;
    };
    let corpus = std::path::Path::new(&home).join("canonical/git/chisel-releases/slices");
    let Ok(entries) = std::fs::read_dir(&corpus) else {
        return;
    };

    let mut sampled = 0usize;
    let mut accepted = 0usize;
    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().and_then(|s| s.to_str()) != Some("yaml") {
            continue;
        }
        let Ok(src) = std::fs::read(&path) else { continue };
        sampled += 1;
        if runtime.detect(&src[..src.len().min(4096)], detect_addr) {
            accepted += 1;
        } else {
            eprintln!("slice_yaml_detect rejected positive sample: {}", path.display());
        }
        if sampled >= 50 {
            break;
        }
    }

    if sampled > 0 {
        assert_eq!(accepted, sampled, "expected every chisel slice sample to be accepted");
    }
}
