use lsh::runtime::Ansi16;

use lsh_defs::HighlightKind;

/// ANSI-16 colormap. maps highlight kinds to escape codes.
/// respects user terminal palettes, works under light and dark themes.
///
/// Colours come from the canonical [`HighlightKind::default_color`] table
/// generated by lsh -- shared with `edit` and any future consumer. Pure-
/// attribute kinds (bold, italic, link, strikethrough) have no foreground
/// colour and are layered on top here.
pub fn color_map() -> Vec<&'static str> {
    let max_kind = (HighlightKind::MarkupStrikethrough as u32)
        .max(HighlightKind::MetaHeader as u32)
        .max(HighlightKind::StorageType as u32)
        .max(HighlightKind::SupportFunction as u32);
    let mut map = vec![""; max_kind as usize + 1];

    for i in 0..=max_kind {
        if let Ok(kind) = HighlightKind::try_from(i)
            && let Some(c) = kind.default_color()
        {
            map[i as usize] = ansi16_sgr(c);
        }
    }

    // Attribute-only kinds: no fg colour, just style escape.
    map[HighlightKind::MarkupBold as usize] = "\x1b[1m";
    map[HighlightKind::MarkupItalic as usize] = "\x1b[3m";
    map[HighlightKind::MarkupLink as usize] = "\x1b[4m";
    map[HighlightKind::MarkupStrikethrough as usize] = "\x1b[9m";

    map
}

fn ansi16_sgr(c: Ansi16) -> &'static str {
    match c {
        Ansi16::Black => "\x1b[30m",
        Ansi16::Red => "\x1b[31m",
        Ansi16::Green => "\x1b[32m",
        Ansi16::Yellow => "\x1b[33m",
        Ansi16::Blue => "\x1b[34m",
        Ansi16::Magenta => "\x1b[35m",
        Ansi16::Cyan => "\x1b[36m",
        Ansi16::White => "\x1b[37m",
        Ansi16::BrightBlack => "\x1b[90m",
        Ansi16::BrightRed => "\x1b[91m",
        Ansi16::BrightGreen => "\x1b[92m",
        Ansi16::BrightYellow => "\x1b[93m",
        Ansi16::BrightBlue => "\x1b[94m",
        Ansi16::BrightMagenta => "\x1b[95m",
        Ansi16::BrightCyan => "\x1b[96m",
        Ansi16::BrightWhite => "\x1b[97m",
    }
}
