// Generates a `Language` enum + `ALL` const from `definitions/*.lsh`,
// for use by the golden test suite. The match-exhaustiveness on
// `Language` turns "added an lsh def, forgot a fixture" into a compile
// error rather than a runtime miss.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let defs = manifest.join("definitions");
    println!("cargo:rerun-if-changed={}", defs.display());

    let mut names: Vec<String> = Vec::new();
    for entry in fs::read_dir(&defs).unwrap() {
        let path = entry.unwrap().path();
        if path.extension().and_then(|e| e.to_str()) != Some("lsh") {
            continue;
        }
        let src = fs::read_to_string(&path).unwrap();
        names.extend(pub_fn_names(&src));
    }
    names.sort();

    let mut code = String::new();
    code.push_str("// auto-generated by crates/lsh/build.rs\n\n");
    code.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n");
    code.push_str("#[allow(dead_code)]\n");
    code.push_str("pub enum Language {\n");
    for n in &names {
        code.push_str(&format!("    {},\n", to_pascal(n)));
    }
    code.push_str("}\n\n");
    code.push_str("#[allow(dead_code)]\n");
    code.push_str("pub const ALL: &[Language] = &[\n");
    for n in &names {
        code.push_str(&format!("    Language::{},\n", to_pascal(n)));
    }
    code.push_str("];\n\n");
    code.push_str("#[allow(dead_code)]\n");
    code.push_str("pub fn entrypoint_name(lang: Language) -> &'static str {\n");
    code.push_str("    match lang {\n");
    for n in &names {
        code.push_str(&format!("        Language::{} => {:?},\n", to_pascal(n), n));
    }
    code.push_str("    }\n");
    code.push_str("}\n");

    let out = PathBuf::from(env::var("OUT_DIR").unwrap()).join("language_enum.rs");
    fs::write(out, code).unwrap();
}

fn pub_fn_names(src: &str) -> Vec<String> {
    let mut names = Vec::new();
    for line in src.lines() {
        let line = line.trim_start();
        if let Some(rest) = line.strip_prefix("pub fn ") {
            let name: String =
                rest.chars().take_while(|c| c.is_ascii_alphanumeric() || *c == '_').collect();
            if !name.is_empty() {
                names.push(name);
            }
        }
    }
    names
}

fn to_pascal(s: &str) -> String {
    let mut out = String::new();
    let mut cap = true;
    for c in s.chars() {
        if c == '_' {
            cap = true;
        } else if cap {
            out.push(c.to_ascii_uppercase());
            cap = false;
        } else {
            out.push(c);
        }
    }
    out
}
